metadata:
  name: taskmanager-chart
  version: 0.1.0
  description: A Helm chart for deploying a MERN stack application
  appVersion: "1.0.0"



clientDeploymentName: client-deployment
serverDeploymentName: server-deployment

clientReplicaCount: 1
clientImage:
  repository: bharadwajreddy1406/mern-client
  tag: latest
  pullPolicy: IfNotPresent

clientSpec:
  ports:
    - containerPort: 80
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"


serverReplicaCount: 2
serverImage:
  repository: bharadwajreddy1406/mern-server
  tag: latest
  pullPolicy: IfNotPresent

serverSpec:
  ports:
    - containerPort: 5000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

