apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    app: server
spec:
  containers:
    - name: mern-server
      image: bharadwajreddy1406/mern-server:latest
      ports:
        - containerPort: 5000
      env:
        - name: MONGODB_URI
          value: "mongodb://use ur mongo url"
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "50m"
          memory: "64Mi"