  # listen bro i think i told u in commands file to read this yaml 
  # so here's what u need to do
  # take your mongodb connection string and encode it in base64
  # how to do it ? ==>  just do this 
  # echo -n "mongodb://mongodb-service:27017/mern" | base64
  # and then paste the output here in place of the value of mongodb-uri

  ### then you are good to go all the best

# check it with this command
# echo -n "encoded string" | base64 --decode

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Base64 encoded mongodb://mongodb-service:27017/mern
  # You can encode your own string with: echo -n "mongodb://mongodb-service:27017/mern" | base64
  mongodb-uri: bW9uZ29kYitzcnY6Ly9iaGFyYWR3YWpyZWRkeTE0NjM6cmVkZHkxNDA2QGNsdXN0ZXIwLjN3MXhiLm1vbmdvZGIubmV0L21lcm4=

  
  # You can add additional secrets here
  # Example for JWT_SECRET
  # jwt-secret: c29tZXNlY3JldGtleQ==