  # listen bro i think i told u in commands file to read this yaml 
  # so here's what u need to do
  # take your mongodb connection string and encode it in base64
  # how to do it ? ==>  just do this 
  # echo -n "mongodb://mongodb-service:27017/mern" | base64
  # and then paste the output here in place of the value of mongodb-uri

  ### then you are good to go all the best

  
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Base64 encoded mongodb://mongodb-service:27017/mern
  # You can encode your own string with: echo -n "mongodb://mongodb-service:27017/mern" | base64
  mongodb-uri: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9tZXJu

  
  # You can add additional secrets here
  # Example for JWT_SECRET
  # jwt-secret: c29tZXNlY3JldGtleQ==