apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: bharadwajreddy1406/node-server:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              valueFrom:
                configMapRef:
                  name: port-config  # Name of your ConfigMap
                  key: port-number  # Key inside the ConfigMap
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
