apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.clientDeploymentName }}
  labels:
    {{- toYaml .Values.client.labels | nindent 4 }}
spec:
  replicas: {{ .Values.clientSpec.replicas }}
  selector:
    matchLabels:
      {{- toYaml .Values.client.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.client.labels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.clientImage.containerName }}
          image: {{ .Values.clientImage.repository }}:{{ .Values.clientImage.tag }}
          ports:
            - containerPort: {{ (index .Values.clientSpec.ports 0).containerPort }}
          resources:
            {{- toYaml .Values.clientSpec.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.clientImage.pullPolicy }}
