apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.service_name }}
  labels:
    {{ toYaml .Values.client.labels | indent 4 }}
spec:
  selector:
    {{ toYaml .Values.client.labels | indent 4 }}
  ports:
    - protocol: {{ .Values.protocol }}
      port: {{ (index .Values.clientSpec.ports 0).containerPort }}
      targetPort: {{ (index .Values.clientSpec.ports 0).targetPort }}
  type: {{ .Values.clientSpec.service_type }}