apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.service_name}}
  labels:
    {{ toYaml .Values.server.labels | indent 4 }}
spec:
  type: {{ .Values.serverSpec.service_type }}

  selector:
    {{ toYaml .Values.server.labels | indent 4 }}

  ports:
    - name: http
      protocol: {{.Values.protocol }}
      port: {{ (index .Values.serverSpec.ports 0).containerPort }}
      targetPort: {{ (index .Values.serverSpec.ports 0).targetPort }}

  sessionAffinity: None

  internalTrafficPolicy: {{ .Values.internalTrafficPolicy }}